GOOGLE_SERVICE_ACCOUNT_FILE = "google-credentials.json"

[algolia]
ALGOLIA_APP_ID = ""
ALGOLIA_API_KEY = ""

[config]
title = My FAQ App
google_sheet_url = link_to_your_google_sheet
google_sheet_name = Sheet1